### ISSUE TITLE
Could it be modified to put the cursor on the address bar of the new tab?

### ISSUE THREAD

**Issue by carehart** [zach-adams/simple-new-tab-url#11] opened 2023-06-08 17:36 UTC
Great job, folks, especially for those who want to use this to create a clean empty new tab (about:blank). One negative, though: the extension does not cause the cursor to be placed in the address bar, so that one can type a new URL. That's indeed how all other "new tab" features in browsers work (Chrome, Firefox, Edge, etc.)

It's a minor thing, sure. But for keyboard folks, being able to do ctrl-t (open a new tab) and then start typing a url--without touching the mouse or tabbing or using a keyboard shortcut to go to the address bar--would just really be the icing on the cake. :-)

I appreciate everyone has their pet features, and being open source code, "anyone can make a pull request". I'll not be digging into that, so if this does capture the fancy of anyone who may, I realize that this idea could die on the vine. Just wanted to put it out there, as a first-day user of the extension. I'll disable it for now, as having the new tab be that blank page in Edge was my only reason for using it, and this lack of the cursor being on the address bar is not a cost worth the benefit. I'm sure it is for many, so again thanks for it.

**Comment by J-PRS** [comment] 2023-10-28 19:37
It's not a minor feature, it's virtually unusable for someone used to ctrl+t -> typing.  I wanted to use this because it doesn't blink white when going from dark site to another dark site, but can't for now.

**Comment by zach-adams** [comment] 2023-10-30 15:46
Sorry haven't had time to take a look at this recently, should have some time to add this soon!

**Comment by zach-adams** [comment] 2023-11-27 18:56
Ok @carehart @J-PRS it should be updated, the latest version (1.2.1) should have a new option for "Enable auto-highlight/select URL on new tab load".
The Chrome Webstore developer dashboard is giving me the usual headaches, it might be a bit until it's updated officially. In the meantime there's a zip file for the latest version in the master branch that you can load unpacked with Chrome's developer mode if you don't want to wait.
Let me know if the feature is working as intended for you

**Comment by J-PRS** [comment] 2023-11-27 19:04
Alright, it's working as intended. Thank you!

**Comment by zach-adams** [comment] 2023-11-28 17:27
Alright update should be published to the Chrome webstore. Closing as fixed.
Thanks for the suggestions/feedback!

**Closed by zach-adams** 2023-11-28 17:27 UTC

**Comment by carehart** [comment] 2023-11-29 18:01
It does indeed solve that problem, which is great to see, thanks. 

(FWIW, I've since found [another extension](https://chromewebstore.google.com/detail/blank-new-tab-page-dark/fhdjnnbfgbgheebemnjaopachfanifhh) that does more simply what I wanted: to have "new tab" open simply to an entirely blank page. 

With yours, a) one has to know to put about:blank into the URL field you offer. Then b) even with this change they do see that about:blank always highlighted on the new tab. The other extension doesn't require or show either; it simply opens a new blank page, which really was my sole goal. I share this info if it may help anyone.) 

Yours is great if one DOES want to set a specific other URL. Again, thanks for it, and for addressing this issue for everyone who may benefit.
